#include "sign_up.h"
#include "login.h"
#include "home.h"
#include "zone1.h"
#include "zone2.h"
#include "zone3.h"
#include "hotel.h"
#include "info.h"
#include "result.h"
#include <windows.h>
#include <string>
#include <fstream> 